FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV ASDF_DIR=/opt/asdf

# Install required packages
RUN apt-get update && apt-get install -y \
    curl git unzip zip build-essential \
    libssl-dev libncurses-dev m4 cmake \
    autoconf libwxgtk3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev \
    libpng-dev libssh-dev unixodbc-dev \
    udev gcc g++ ssh locales \
    wget gnupg ca-certificates \
    libreadline-dev pkg-config nano squashfs-tools file cpio rsync bc\
    && apt-get clean

# Set locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

# Install ASDF
RUN git clone https://github.com/asdf-vm/asdf.git $ASDF_DIR --branch v0.14.0
ENV PATH="$ASDF_DIR/bin:$ASDF_DIR/shims:$PATH"

# Add ASDF plugins and install Erlang/Elixir
ARG ERLANG_VERSION=27.3.4.2
ARG ELIXIR_VERSION=1.17.3-otp-27

RUN bash -c ". $ASDF_DIR/asdf.sh && \
    asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git && \
    asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git && \
    export KERL_BUILD_DOCS=no && \
    export KERL_CONFIGURE_OPTIONS='--disable-debug --without-javac' && \
    asdf install erlang $ERLANG_VERSION && \
    asdf global erlang $ERLANG_VERSION && \
    asdf install elixir $ELIXIR_VERSION && \
    asdf global elixir $ELIXIR_VERSION"

# Install fwup 1.10.1
RUN wget https://github.com/fwup-home/fwup/releases/download/v1.10.1/fwup_1.10.1_amd64.deb && \
    dpkg -i fwup_1.10.1_amd64.deb || apt-get install -f -y && \
    rm fwup_1.10.1_amd64.deb


# Setup shell init for asdf
RUN echo ". $ASDF_DIR/asdf.sh" >> /etc/profile

# Install Hex, Rebar, and Nerves Bootstrap
RUN bash -c ". $ASDF_DIR/asdf.sh && \
    mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex nerves_bootstrap --force"

RUN echo '\n. /opt/asdf/asdf.sh' >> /etc/bash.bashrc
# Set working directory
WORKDIR /work

# Default command
CMD ["/bin/bash"]
