name: Build Nerves C2 Firmware

on:
  push:
    branches:
      - '*_ci'
      - 'develop2'
  pull_request:
    branches:
      - '*_ci'
      - 'develop2'
  workflow_dispatch:

jobs:
  build-nerves-c2:
    runs-on: ubuntu-latest
    env:
      CI_GITHUB_USER: ${{ github.actor }}
      CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

    steps:
      
      # Step 1: clean cache
      - name: Clean stale cache
        run: rm -rf _build deps
      
      # Step 1b: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Ensure CI SSH key exists
      - name: Ensure CI SSH key exists
        run: |
          mkdir -p ~/.ssh
          if [ -z "$(ls ~/.ssh/*.pub 2>/dev/null)" ]; then
            ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519
          fi

      # Step 3: Build the C2 Docker image with matching UID/GID
      - name: Build C2 Docker image
        run: |
          export CI_UID=$(id -u)
          export CI_GID=$(id -g)
          docker build \
            --build-arg USER_UID=${CI_UID} \
            --build-arg USER_GID=${CI_GID} \
            -t c2_dev \
            -f scripts/docker/Dockerfile.c2 \
            scripts/docker

      # Build firmware inside container
      - name: Run firmware build inside Docker container
        run: |
          chmod +x ./scripts/docker/ci_run.sh
          ./scripts/docker/ci_run.sh ci  \
            "bash /work/nerves_system_c2/scripts/c2_build.sh local"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-artifacts
          path: artifacts/
